In [1]:
# importaciones básicas
import numpy as np
import pandas as pd

In [3]:
var_precio_alq = pd.read_csv('./data/dataset4_var_precio_alq.csv', sep=';')
var_precio_alq

,Localización,Precio m2 dic 2022 Eur/m2,Variación mensual,Variación trimestral,Variación anual,Máximo histórico Eur/m2,Variación máximo
0,España,11.4,1.5,2.0,8.4,11.5,0.3
1,Andalucía,9.6,1.7,6.2,9.8,9.6,0.0
2,Aragón,8.3,0.0,0.5,4.4,8.3,-0.4
3,Asturias,7.9,-0.2,0.7,4.9,10.8,-26.9
4,Baleares,13.8,0.7,2.5,14.5,14.0,-1.3
5,Canarias,11.8,1.0,4.5,14.2,11.8,0.0
6,Cantabria,8.9,2.1,-7.6,7.7,12.7,-30.0
7,Castilla y León,7.1,-0.5,-2.0,4.3,7.3,-2.6
8,Castilla-La Mancha,6.1,0.0,-1.0,4.3,6.2,-1.0
9,Cataluña,15.6,2.8,4.2,14.7,15.6,0.0
10,Comunitat Valenciana,9.0,1.4,0.9,15.8,9.4,-4.1
11,Euskadi,12.8,0.8,1.2,4.5,12.8,0.0
12,Extremadura,5.8,0.1,1.9,5.7,5.8,0.0
13,Galicia,7.7,1.1,1.7,5.1,8.7,-11.6
14,La Rioja,7.2,1.5,-2.3,6.0,7.4,-2.3
15,Madrid Comunidad,14.9,-0.3,-1.8,9.6,15.4,-3.2
16,Melilla,9.3,2.8,2.3,2.8,9.5,-2.6
17,Murcia Región,7.0,-1.0,-6.5,7.1,7.6,-7.9
18,Navarra,9.3,0.5,0.0,3.0,9.4,-0.8

In [4]:
var_precio_alq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Localización               19 non-null     object
 1   Precio m2 dic 2022 Eur/m2  19 non-null     float64
 2   Variación mensual          19 non-null     float64
 3   Variación trimestral       19 non-null     float64
 4   Variación anual            19 non-null     float64
 5   Máximo histórico Eur/m2    19 non-null     float64
 6   Variación máximo           19 non-null     float64
dtypes: float64(6), object(1)
memory usage: 1.2+ KB

In [5]:
var_precio_alq.describe()

,Precio m2 dic 2022 Eur/m2,Variación mensual,Variación trimestral,Variación anual,Máximo histórico Eur/m2,Variación máximo
count,19.000000,19.000000,19.000000,19.000000,19.00000,19.000000
mean,9.657895,0.842105,0.389474,7.726316,10.20000,-4.968421
std,2.931309,1.078742,3.432022,4.241310,2.93087,8.822323
min,5.800000,-1.000000,-7.600000,2.800000,5.80000,-30.000000
25%,7.450000,0.000000,-1.400000,4.450000,7.95000,-3.650000
50%,9.000000,0.800000,0.900000,6.000000,9.50000,-1.300000
75%,11.600000,1.500000,2.150000,9.700000,12.25000,0.000000
max,15.600000,2.800000,6.200000,15.800000,15.60000,0.300000

In [6]:
var_precio_alq.columns

Index(['Localización', 'Precio m2 dic 2022 Eur/m2', 'Variación mensual',
       'Variación trimestral', 'Variación anual', 'Máximo histórico Eur/m2',
       'Variación máximo'],
      dtype='object')

In [7]:
var_precio_alq.rename(columns={'Precio m2 dic 2022 Eur/m2':'precio_eur', 
                                     'Variación mensual': 'var_mensual_per', 
                                     'Variación trimestral': 'var_trim_per', 
                                     'Variación anual': 'var_anual_per', 
                                     'Máximo histórico Eur/m2': 'precio_max_eur',  
                                     'Variación máximo': 'var_max_per'}, inplace=True)

In [8]:
var_precio_alq

,Localización,precio_eur,var_mensual_per,var_trim_per,var_anual_per,precio_max_eur,var_max_per
0,España,11.4,1.5,2.0,8.4,11.5,0.3
1,Andalucía,9.6,1.7,6.2,9.8,9.6,0.0
2,Aragón,8.3,0.0,0.5,4.4,8.3,-0.4
3,Asturias,7.9,-0.2,0.7,4.9,10.8,-26.9
4,Baleares,13.8,0.7,2.5,14.5,14.0,-1.3
5,Canarias,11.8,1.0,4.5,14.2,11.8,0.0
6,Cantabria,8.9,2.1,-7.6,7.7,12.7,-30.0
7,Castilla y León,7.1,-0.5,-2.0,4.3,7.3,-2.6
8,Castilla-La Mancha,6.1,0.0,-1.0,4.3,6.2,-1.0
9,Cataluña,15.6,2.8,4.2,14.7,15.6,0.0
10,Comunitat Valenciana,9.0,1.4,0.9,15.8,9.4,-4.1
11,Euskadi,12.8,0.8,1.2,4.5,12.8,0.0
12,Extremadura,5.8,0.1,1.9,5.7,5.8,0.0
13,Galicia,7.7,1.1,1.7,5.1,8.7,-11.6
14,La Rioja,7.2,1.5,-2.3,6.0,7.4,-2.3
15,Madrid Comunidad,14.9,-0.3,-1.8,9.6,15.4,-3.2
16,Melilla,9.3,2.8,2.3,2.8,9.5,-2.6
17,Murcia Región,7.0,-1.0,-6.5,7.1,7.6,-7.9
18,Navarra,9.3,0.5,0.0,3.0,9.4,-0.8

In [ ]:
var_precio_alq.to_csv('./data/clean/var_precio_alq.csv', encoding='utf-8', index=False)