## Dataset de Sobrecoste de la vivienda 
### Tasa de sobrecarga del costo de la vivienda por estado de tenencia: encuesta EU-SILC.
### Unidades: porcentaje

Fuente: Eurostat. Ref: ILC_LVHO07C

In [68]:
# importaciones b√°sicas
import numpy as np
import pandas as pd

# pd.set_option('max_rows', None)
pd.set_option('max_columns', None)
# pd.set_option('display.width', None)
# pd.set_option('display.max_colwidth', None)

In [44]:
sobrecoste_v = pd.read_csv('../../src/data/dataset9_sobrecoste_v.csv', sep=';')
sobrecoste_v

,TIME,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Belgium,37.2,34.0,38.1,33.7,36.0,34.9,34.8,30.5,29.4,30.1
1,Bulgaria,48.2,36.3,40.8,30.8,50.4,51.0,50.1,41.0,44.8,45.4
2,Czechia,28.2,32.7,29.9,31.0,29.3,28.3,27.9,24.1,25.8,26.1
3,Denmark,34.7,37.1,32.9,31.9,31.6,31.7,28.9,30.7,25.2,30.3
4,Estonia,27.9,25.6,32.3,42.3,28.5,26.6,25.5,28.1,36.5,26.1
5,Ireland,21.3,16.6,19.1,17.7,19.3,21.5,14.3,17.8,16.7,10.6
6,Greece,53.0,58.3,87.5,86.8,84.6,83.9,83.1,83.2,79.2,74.6
7,Spain,44.7,42.3,47.5,43.3,43.0,42.1,38.1,37.4,35.9,40.9
8,France,16.2,16.2,15.8,14.9,16.5,14.7,14.9,17.7,18.2,-
9,Croatia,40.5,49.8,41.3,36.4,45.2,48.6,32.1,35.7,20.9,19.5
10,Italy,34.2,34.2,32.4,32.7,32.2,28.2,29.1,29.2,28.1,26.2
11,Cyprus,19.9,17.7,19.3,19.7,18.1,14.2,11.3,12.3,10.5,15.3
12,Latvia,18.1,17.1,15.1,13.6,13.0,11.2,11.5,8.3,13.5,10.7
13,Lithuania,55.7,23.5,37.3,30.3,48.3,42.5,30.9,21.9,19.5,12.4
14,Luxembourg,17.1,21.4,26.3,23.2,25.0,26.0,30.2,30.6,26.3,15.0
15,Hungary,38.5,37.3,41.4,32.4,36.6,30.6,46.9,22.4,46.4,14.2
16,Malta,21.1,25.9,22.6,14.6,22.3,13.9,12.1,17.6,13.3,13.6
17,Netherlands,19.7,23.2,24.8,25.0,28.0,26.2,25.6,27.0,22.8,48.3
18,Austria,17.3,15.5,15.6,15.3,15.6,15.5,14.5,14.8,12.7,13.1
19,Poland,27.1,28.5,25.5,26.3,24.5,23.6,26.4,26.9,19.7,20.7
20,Portugal,35.8,35.2,33.8,35.4,31.9,28.2,25.8,26.3,19.7,26.9
21,Romania,72.7,54.4,42.0,45.7,36.3,60.4,46.3,39.8,41.9,39.3
22,Slovenia,26.6,25.8,27.4,25.9,29.0,24.3,21.7,19.4,18.6,17.6
23,Slovakia,15.1,12.9,14.9,8.4,13.9,20.9,19.2,16.4,15.9,-
24,Finland,11.8,15.0,16.8,16.7,14.6,13.0,15.2,13.1,14.2,12.8
25,Sweden,17.3,18.1,17.7,18.7,18.0,19.3,18.8,19.8,18.0,18.8
26,Iceland,18.1,17.9,18.6,19.5,16.9,21.1,17.4,-,-,-
27,Norway,29.8,28.7,34.2,36.2,33.6,32.3,35.4,32.9,30.9,-
28,Switzerland,16.6,15.2,17.3,17.2,18.2,19.6,19.4,20.6,20.0,-
29,United Kingdom,23.8,25.3,34.6,37.1,35.4,38.6,37.7,-,-,-
30,Montenegro,-,55.1,56.4,59.1,60.0,52.0,51.7,40.8,46.7,-
31,North Macedonia,58.8,62.4,64.0,43.8,29.0,56.2,38.1,61.9,36.0,-
32,Albania,-,-,-,-,-,41.5,32.7,35.0,27.1,-
33,Serbia,-,62.4,67.5,65.5,70.3,63.5,71.0,56.3,62.3,-
34,T√ºrkiye,37.4,44.4,39.4,36.1,34.4,32.4,32.1,33.0,29.2,-

In [4]:
sobrecoste_v.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TIME    35 non-null     object
 1   2012    35 non-null     object
 2   2013    35 non-null     object
 3   2014    35 non-null     object
 4   2015    35 non-null     object
 5   2016    35 non-null     object
 6   2017    35 non-null     float64
 7   2018    35 non-null     float64
 8   2019    35 non-null     object
 9   2020    35 non-null     object
 10  2021    35 non-null     object
dtypes: float64(2), object(9)
memory usage: 3.1+ KB

In [5]:
sobrecoste_v.columns

Index(['TIME', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021'],
      dtype='object')

In [45]:
sobrecoste_v.index = sobrecoste_v['TIME']

In [46]:
sobrecoste_v.drop(columns='TIME', inplace=True)

In [47]:
sobrecoste_v_T = sobrecoste_v.T

In [48]:
sobrecoste_v_T

TIME,Belgium,Bulgaria,Czechia,Denmark,Estonia,Ireland,Greece,Spain,France,Croatia,...,Sweden,Iceland,Norway,Switzerland,United Kingdom,Montenegro,North Macedonia,Albania,Serbia,T√ºrkiye
2012,37.2,48.2,28.2,34.7,27.9,21.3,53.0,44.7,16.2,40.5,...,17.3,18.1,29.8,16.6,23.8,-,58.8,-,-,37.4
2013,34.0,36.3,32.7,37.1,25.6,16.6,58.3,42.3,16.2,49.8,...,18.1,17.9,28.7,15.2,25.3,55.1,62.4,-,62.4,44.4
2014,38.1,40.8,29.9,32.9,32.3,19.1,87.5,47.5,15.8,41.3,...,17.7,18.6,34.2,17.3,34.6,56.4,64.0,-,67.5,39.4
2015,33.7,30.8,31.0,31.9,42.3,17.7,86.8,43.3,14.9,36.4,...,18.7,19.5,36.2,17.2,37.1,59.1,43.8,-,65.5,36.1
2016,36.0,50.4,29.3,31.6,28.5,19.3,84.6,43.0,16.5,45.2,...,18.0,16.9,33.6,18.2,35.4,60.0,29.0,-,70.3,34.4
2017,34.9,51.0,28.3,31.7,26.6,21.5,83.9,42.1,14.7,48.6,...,19.3,21.1,32.3,19.6,38.6,52.0,56.2,41.5,63.5,32.4
2018,34.8,50.1,27.9,28.9,25.5,14.3,83.1,38.1,14.9,32.1,...,18.8,17.4,35.4,19.4,37.7,51.7,38.1,32.7,71.0,32.1
2019,30.5,41.0,24.1,30.7,28.1,17.8,83.2,37.4,17.7,35.7,...,19.8,-,32.9,20.6,-,40.8,61.9,35.0,56.3,33.0
2020,29.4,44.8,25.8,25.2,36.5,16.7,79.2,35.9,18.2,20.9,...,18.0,-,30.9,20.0,-,46.7,36.0,27.1,62.3,29.2
2021,30.1,45.4,26.1,30.3,26.1,10.6,74.6,40.9,-,19.5,...,18.8,-,-,-,-,-,-,-,-,-

In [49]:
sobrecoste_v_T['France'].astype('float', errors='ignore')

2012    16.2
2013    16.2
2014    15.8
2015    14.9
2016    16.5
2017    14.7
2018    14.9
2019    17.7
2020    18.2
2021       -
Name: France, dtype: object

In [50]:
for column in sobrecoste_v_T:
    sobrecoste_v_T[column] = sobrecoste_v_T[column].astype('float',errors= 'ignore')

In [51]:
sobrecoste_v_T.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 2012 to 2021
Data columns (total 35 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Belgium          10 non-null     float64
 1   Bulgaria         10 non-null     float64
 2   Czechia          10 non-null     float64
 3   Denmark          10 non-null     float64
 4   Estonia          10 non-null     float64
 5   Ireland          10 non-null     float64
 6   Greece           10 non-null     float64
 7   Spain            10 non-null     float64
 8   France           10 non-null     object
 9   Croatia          10 non-null     float64
 10  Italy            10 non-null     float64
 11  Cyprus           10 non-null     float64
 12  Latvia           10 non-null     float64
 13  Lithuania        10 non-null     float64
 14  Luxembourg       10 non-null     float64
 15  Hungary          10 non-null     float64
 16  Malta            10 non-null     float64
 17  Netherlands      10 non-null     float64
 18  Austria          10 non-null     float64
 19  Poland           10 non-null     float64
 20  Portugal         10 non-null     float64
 21  Romania          10 non-null     float64
 22  Slovenia         10 non-null     float64
 23  Slovakia         10 non-null     object
 24  Finland          10 non-null     float64
 25  Sweden           10 non-null     float64
 26  Iceland          10 non-null     object
 27  Norway           10 non-null     object
 28  Switzerland      10 non-null     object
 29  United Kingdom   10 non-null     object
 30  Montenegro       10 non-null     object
 31  North Macedonia  10 non-null     object
 32  Albania          10 non-null     object
 33  Serbia           10 non-null     object
 34  T√ºrkiye          10 non-null     object
dtypes: float64(24), object(11)
memory usage: 3.1+ KB

In [52]:
sobrecoste_v_T['France']

2012    16.2
2013    16.2
2014    15.8
2015    14.9
2016    16.5
2017    14.7
2018    14.9
2019    17.7
2020    18.2
2021       -
Name: France, dtype: object

In [53]:
sobrecoste_v_T['France'] = sobrecoste_v_T['France'].map({'16.2':float(16.2),
                                                        '16.2':float(16.2),
                                                        '15.8':float(15.8),
                                                        '14.9':float(14.9),
                                                        '16.5':float(16.5),
                                                        '14.7':float(14.7),
                                                        '14.9':float(14.9),
                                                        '17.7':float(17.7),
                                                        '18.2':float(18.2)})

In [54]:
sobrecoste_v_T

TIME,Belgium,Bulgaria,Czechia,Denmark,Estonia,Ireland,Greece,Spain,France,Croatia,...,Sweden,Iceland,Norway,Switzerland,United Kingdom,Montenegro,North Macedonia,Albania,Serbia,T√ºrkiye
2012,37.2,48.2,28.2,34.7,27.9,21.3,53.0,44.7,16.2,40.5,...,17.3,18.1,29.8,16.6,23.8,-,58.8,-,-,37.4
2013,34.0,36.3,32.7,37.1,25.6,16.6,58.3,42.3,16.2,49.8,...,18.1,17.9,28.7,15.2,25.3,55.1,62.4,-,62.4,44.4
2014,38.1,40.8,29.9,32.9,32.3,19.1,87.5,47.5,15.8,41.3,...,17.7,18.6,34.2,17.3,34.6,56.4,64.0,-,67.5,39.4
2015,33.7,30.8,31.0,31.9,42.3,17.7,86.8,43.3,14.9,36.4,...,18.7,19.5,36.2,17.2,37.1,59.1,43.8,-,65.5,36.1
2016,36.0,50.4,29.3,31.6,28.5,19.3,84.6,43.0,16.5,45.2,...,18.0,16.9,33.6,18.2,35.4,60.0,29.0,-,70.3,34.4
2017,34.9,51.0,28.3,31.7,26.6,21.5,83.9,42.1,NaN,48.6,...,19.3,21.1,32.3,19.6,38.6,52.0,56.2,41.5,63.5,32.4
2018,34.8,50.1,27.9,28.9,25.5,14.3,83.1,38.1,NaN,32.1,...,18.8,17.4,35.4,19.4,37.7,51.7,38.1,32.7,71.0,32.1
2019,30.5,41.0,24.1,30.7,28.1,17.8,83.2,37.4,17.7,35.7,...,19.8,-,32.9,20.6,-,40.8,61.9,35.0,56.3,33.0
2020,29.4,44.8,25.8,25.2,36.5,16.7,79.2,35.9,18.2,20.9,...,18.0,-,30.9,20.0,-,46.7,36.0,27.1,62.3,29.2
2021,30.1,45.4,26.1,30.3,26.1,10.6,74.6,40.9,NaN,19.5,...,18.8,-,-,-,-,-,-,-,-,-

In [62]:
values = {'2017':14.7, '2018':14.9,'2021':'-'}

In [64]:
sobrecoste_v_T['France'] = sobrecoste_v_T['France'].fillna(value=values)

In [69]:
sobrecoste_v_T.tail(3)

TIME,Belgium,Bulgaria,Czechia,Denmark,Estonia,Ireland,Greece,Spain,France,Croatia,Italy,Cyprus,Latvia,Lithuania,Luxembourg,Hungary,Malta,Netherlands,Austria,Poland,Portugal,Romania,Slovenia,Slovakia,Finland,Sweden,Iceland,Norway,Switzerland,United Kingdom,Montenegro,North Macedonia,Albania,Serbia,T√ºrkiye
2019,30.5,41.0,24.1,30.7,28.1,17.8,83.2,37.4,17.7,35.7,29.2,12.3,8.3,21.9,30.6,22.4,17.6,27.0,14.8,26.9,26.3,39.8,19.4,16.4,13.1,19.8,-,32.9,20.6,-,40.8,61.9,35.0,56.3,33.0
2020,29.4,44.8,25.8,25.2,36.5,16.7,79.2,35.9,18.2,20.9,28.1,10.5,13.5,19.5,26.3,46.4,13.3,22.8,12.7,19.7,19.7,41.9,18.6,15.9,14.2,18.0,-,30.9,20.0,-,46.7,36.0,27.1,62.3,29.2
2021,30.1,45.4,26.1,30.3,26.1,10.6,74.6,40.9,-,19.5,26.2,15.3,10.7,12.4,15.0,14.2,13.6,48.3,13.1,20.7,26.9,39.3,17.6,-,12.8,18.8,-,-,-,-,-,-,-,-,-

In [ ]:
sobrecoste_v_T.to_csv('../data/clean/sobrecoste_v.csv', encoding='utf-8', index=False)