In [1]:
# importaciones básicas
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('./data/teicp040.tsv', sep='\t')
df

,"coicop,unit,geo\time",2021M12,2022M01,2022M02,2022M03,2022M04,2022M05,2022M06,2022M07,2022M08,2022M09,2022M10,2022M11
0,"CP04,I15,AL",109.11 d,109.52 d,109.53 d,111.07 d,111.51 d,111.59 d,111.29 d,111.55 d,112.18 d,112.98 d,113.28 d,:
1,"CP04,I15,AT",116.64,118.25,122.28,124.45,124.57,124.28,125.53,128.93,130.69,141.92,142.59,141.78
2,"CP04,I15,BE",133.26,147.14,148.77,148.96,148.16,150.53,151.61,151.18,155.37,165.95,180.99,168.28
3,"CP04,I15,BG",123.61,126.02,125.75,127.32,129.77,131.80,132.57,138.67,146.32,152.18,147.75,144.27
4,"CP04,I15,CH",105.84,107.09,107.53,108.01,108.56,109.11,109.57,109.86,110.16,109.97,110.95,110.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,"CP04,PCH_M12,SI",8.5,11.1,13.8,1.1,6.4,11.1,25.8,27.0,28.2,18.9,18.7,18.4
122,"CP04,PCH_M12,SK",-1.2,10.7,11.0,11.9,12.6,12.8,13.2,13.4,14.1,14.6,15.1,15.5
123,"CP04,PCH_M12,TR",28.6 d,48.4 d,49.7 d,51.4 d,61.1 d,63.5 d,75.1 d,70.0 d,71.9 d,84.7 d,85.2 d,82.9 d
124,"CP04,PCH_M12,US",5.6 d,6.8 d,6.7 d,7.4 d,7.8 d,9.0 d,10.3 d,10.2 d,10.7 d,10.9 d,10.1 d,9.9 d
125,"CP04,PCH_M12,XK",4.8 d,8.7 d,9.0 d,15.7 d,14.2 d,12.8 d,9.9 d,11.5 d,12.6 d,14.5 d,14.4 d,: